export const postsData = [
  {
    content: '',
    language: 'DE',
    ord: 12,
    page_id: 58,
    post_id: 0,
    title: 'dvs',
    type: 'booking',
  },
  {
    content:
      '<p class="ql-align-center">Unsere Bar ist gleichzeitig die Rezeption der Herberge und hat täglich ab 16 Uhr geöffnet.</p><p class="ql-align-center">Hier könnt ihr Billard spielen, dem Alkohol frönen oder einen unserer vielen Säfte probieren.</p><p class="ql-align-center">Gute Musik gibts for free!! ;-)</p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><img src="/pictures/bar 2_1635330388615.jpg"></p>',
    language: 'DE',
    ord: 1,
    page_id: 2,
    post_id: 2,
    title: '',
    type: 'article',
  },
  {
    content:
      '<p>Die Hostel - Ein Wohnzimmer mit Übernachtungsmöglichkeiten.</p><p>Die insgesamt 6 Zimmer mit Platz für jeweils 1-5 Personen wurden liebevoll von verschiedenen Berliner Künstlern gestaltet.</p><p>Sowohl durchgerockte Musiker on Tour als auch aufgeschlossene Touristen sollen sich bei uns wohlfühlen.</p><p>Das Konzept ist simpel: wir haben für Musiker und Musikliebhaber, einen Platz geschaffen, an dem sie sich einfach nur wie zuhause fühlen können. Gerade für Bands auf längerer Tour bietet unsere Rock\' n\' Roll Herberge eine Alternative zum engen Nightliner und den unpersönlichen Hotels. Es gibt in allen Zimmern W-Lan. Für unsere Barbesucher gibt es&nbsp;im Sommer vor dem Haus eine Außenbewirtschaftung auf dem Gehweg. Unsere Hausbar bietet täglich bis in die Morgenstunden eine reichhaltige Auswahl an Getränken an.</p><p>In diesem Sinne freuen wir uns, auch Dich und Deine Freunde bald hier bei uns willkommen zu heißen.</p><p class="ql-align-justify"><br></p><p class="ql-align-justify">Wir hoffen auf Euer Verständnis!</p><p><br></p><p><img src="/pictures/bar 1_1635330104587.jpg"></p><p><br></p><h2 class="ql-align-right">Euer Hostel Team</h2><p><br></p><p><br></p><h2><strong>Achtung:</strong>&nbsp;<em>Nazis, Faschisten, Rassisten, Homophobe, Sexisten und jegliche wie auch immer gearteten intoleranten Spießer müssen draußen bleiben.</em></h2><p class="ql-align-justify"><br></p><p class="ql-align-justify"><br></p>',
    language: 'DE',
    ord: 1,
    page_id: 1,
    post_id: 8,
    title: 'The Hostel - Die Absteige für Rockstars & Hosenträger',
    type: 'article',
  },
  {
    content:
      '<h1>Booking companies</h1><p class="ql-align-justify"><a href="http://www.destiny-tourbooking.com/" rel="noopener noreferrer" target="_blank">Destiny Tourbooking</a></p><p class="ql-align-justify"><a href="http://www.koeterhai.de/" rel="noopener noreferrer" target="_blank">Köterhai Booking</a></p><p class="ql-align-justify"><a href="http://www.mad-tourbooking.de/" rel="noopener noreferrer" target="_blank">M.A.D. Tourbooking</a></p><p class="ql-align-justify"><a href="http://www.muttis-booking.com/" rel="noopener noreferrer" target="_blank">Mutti\'s Booking</a></p><p class="ql-align-justify"><a href="http://www.trinityconcerts.de/" rel="noopener noreferrer" target="_blank">Trinity Music</a></p><p class="ql-align-justify"><a href="http://www.universal-music.de/" rel="noopener noreferrer" target="_blank">Universal Music</a></p><p class="ql-align-justify"><a href="http://www.weird-world.de/" rel="noopener noreferrer" target="_blank">Weird World</a></p><p class="ql-align-justify"><a href="http://www.phonocaster.com/" rel="noopener noreferrer" target="_blank">Phonocaster Music</a></p><h1>Recordlabels</h1><p class="ql-align-justify"><a href="http://www.coretexrecords.com/" rel="noopener noreferrer" target="_blank">Coretex Records</a></p><p class="ql-align-justify"><a href="http://www.monotonstudio-records.de/" rel="noopener noreferrer" target="_blank">Monotonstudio Records</a></p><h1>Event locations (Berlin)</h1><p class="ql-align-justify"><a href="http://super.tacheles.de/cms/" rel="noopener noreferrer" target="_blank">Tacheles</a></p><p class="ql-align-justify"><a href="http://www.clash-berlin.de/" rel="noopener noreferrer" target="_blank">Clash</a></p><p class="ql-align-justify"><a href="http://www.bi-nuu.de/" rel="noopener noreferrer" target="_blank">Bi Nuu</a></p><p class="ql-align-justify"><a href="http://www.lido-berlin.de/" rel="noopener noreferrer" target="_blank">Lido</a></p><p class="ql-align-justify"><a href="http://www.astra-berlin.de/" rel="noopener noreferrer" target="_blank">Astra Kulturhaus</a></p><p class="ql-align-justify"><a href="http://koepi137.net/" rel="noopener noreferrer" target="_blank">Köpi</a></p><p class="ql-align-justify"><a href="http://www.so36.de/" rel="noopener noreferrer" target="_blank">SO36</a></p><p class="ql-align-justify"><a href="http://www.tommyhaus.org/" rel="noopener noreferrer" target="_blank">Tommyhaus</a></p><p class="ql-align-justify"><a href="http://www.trinkteufel.de/" rel="noopener noreferrer" target="_blank">Trinkteufel</a></p><p class="ql-align-justify"><a href="http://www.wildatheartberlin.de/" rel="noopener noreferrer" target="_blank">Wild at Heart</a></p><p class="ql-align-justify"><a href="http://www.weissetaube-berlin.de/" rel="noopener noreferrer" target="_blank">Weisse Taube</a></p><p class="ql-align-justify"><a href="http://www.myspace.com/cortinabobberlin/" rel="noopener noreferrer" target="_blank">Cortina Bob</a></p><p class="ql-align-justify"><a href="http://www.festsaal-kreuzberg.de/" rel="noopener noreferrer" target="_blank">Festsaal Kreuzberg</a></p><p class="ql-align-justify"><a href="http://www.rigaer94.squat.net/" rel="noopener noreferrer" target="_blank">R94 (former squat)</a></p><p class="ql-align-justify"><a href="http://www.augspurger-muehle.de/" rel="noopener noreferrer" target="_blank">Augspurger Mühle (beer garden &amp; restaurant)</a></p><h1>Other</h1><p class="ql-align-justify"><a href="http://www.alternativeberlin.com/" rel="noopener noreferrer" target="_blank">Alternative berlin tours</a></p><p class="ql-align-justify"><a href="http://www.sallys.net/" rel="noopener noreferrer" target="_blank">Unclesally*s (Music Magazin)</a></p><p class="ql-align-justify"><a href="http://www.skanstulls.se/" rel="noopener noreferrer" target="_blank">Skanstulls (Hostel in Stockholm)</a></p><p class="ql-align-justify"><a href="http://www.flyerei-berlin.de/" rel="noopener noreferrer" target="_blank">Flyerei Berlin</a></p><p class="ql-align-justify"><a href="http://www.ghettopimps.de/" rel="noopener noreferrer" target="_blank">Ghettopimps (Graffiti-art)</a></p><p class="ql-align-justify"><a href="http://www.augspurger-muehle.de/" rel="noopener noreferrer" target="_blank">Augspurger Mühle (beer garden &amp; restaurant)</a></p><p><br></p>',
    language: 'DE',
    ord: 1,
    page_id: 8,
    post_id: 12,
    title: 'Want to explore more of Berlin?',
    type: 'article',
  },
  {
    content:
      '<p>Hausmarke 0,4l (auch Radler oder Diesel) 2.80</p><p>Pilsner Urquell 0,3l (auch Radler oder Diesel) 2.60</p><p>Pilsner Urquell 0,5l (auch Radler oder Diesel) 3.60</p><p>Rothaus Pils 0,3l (auch Radler oder Diesel) 2.80</p><p>Rothaus Pils 0,5l (auch Radler oder Diesel) 3.80</p><p>Rollberg Rotbier 0,3l 2.90</p><p>Rollberg Rotbier 0,5l 3.90</p><p>Snakebite 0,5l 4.70</p>',
    language: 'DE',
    ord: 4,
    page_id: 2,
    post_id: 15,
    title: 'Vom fass',
    type: 'drinks',
  },
  {
    content:
      '<p>Täglich von 16 Uhr bis Open End!</p><p><br></p><p>Am 15.05. geschlossen.</p><p><br></p>',
    language: 'DE',
    ord: 2,
    page_id: 2,
    post_id: 16,
    title: 'Öffnungszeiten',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/backbord-menü-deutsch-web_1650966815543_1650967100437.jpg"></p>',
    language: 'DE',
    ord: 1,
    page_id: 4,
    post_id: 17,
    title: 'Jeden Dienstag',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/jeden donnerstag_1629460406389.jpg"></p>',
    language: 'DE',
    ord: 2,
    page_id: 4,
    post_id: 18,
    title: 'Jeden Donnerstag',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-justify">Die angegebenen Zimmerpreise sind inklusive MwSt. und Citytax. Sie beziehen sich auf eine Nacht.</p><p class="ql-align-justify">Mehrbettzimmer für 3-5 Personen auf Anfrage möglich.</p><p class="ql-align-justify">Bitte habt Verständnis dafür, dass bei kurzfristiger Absage (3 Tage oder weniger vor Anreise) bzw. Nichtanreise eine Stornogebühr anfällt. Näheres findet Ihr in unseren&nbsp;<a href="http://www.rnrherberge.de/index.php?id=39" rel="noopener noreferrer" target="_blank" style="color: rgb(193, 21, 21)"><em>AGBs</em></a>.</p><p class="ql-align-justify">Check in ab&nbsp;17&nbsp;Uhr, checkout bis 14 Uhr, dafür einfach den&nbsp;Schlüssel von innen in der Zimmertüre stecken lassen.</p><p class="ql-align-justify">Bei Late Check in nach 0&nbsp;Uhr ruft bitte kurz an unter&nbsp;030-XXX XX 00&nbsp;</p><p class="ql-align-justify">Die Zimmer werden nie an mehrere unterschiedliche Gruppen oder Einzelpersonen vermietet.&nbsp;D.h. auch wenn ein Zimmer für bis zu 2 Personen buchbarist, habt Ihr es trotzdem auf jeden Fall für Euch, auch wenn Ihr es alleine bucht!</p><p class="ql-align-justify"><br></p><p class="ql-align-center"><span style="color: rgb(193, 21, 21);">ACHTUNG:</span></p><p class="ql-align-center"><span style="color: black; ">Manchmal kann es bis zu 48 Stunden dauern, bis wir uns bei Euch zurückmelden. </span></p><p class="ql-align-center"><span style="color: black;">Wenn ihr also ein Zimmer am selben Tag der Anfrage oder für den nächsten Tag buchen wollt, ruft bitte unter der 030-XXX XX 00 ab 16 Uhr an, um es telefonisch zu buchen.</span></p><p class="ql-align-center"><br></p><p class="ql-align-justify"><br></p></strong></h2>',
    language: 'DE',
    ord: 1,
    page_id: 5,
    post_id: 19,
    title: 'Hier ein Überblick über unsere Zimmer',
    type: 'article',
  },
  {
    content:
      '<p>Zimmer 1: EG, 140er Matratze oben, 90er Matratze unten, Dusche/WC im Zimmer integriert (nicht abschließbar)</p><p><br></p><p>1 Person&nbsp;- 38,- € Zimmerpreis pro Nacht</p><p>2 Personen&nbsp;- 54€ Zimmerpreis pro Nacht</p><p>3 Personen&nbsp;- 66€ Zimmerpreis pro Nacht</p><p><br></p><p><img src="/pictures/test_1631018785594.jpg"> <img src="/pictures/test2_1631018798589.jpg"></p>',
    language: 'DE',
    ord: 2,
    page_id: 5,
    post_id: 20,
    title: 'Zimmer 1',
    type: 'article',
  },
  {
    content:
      '<p>Zimmer 3: 1. OG, 1 Doppelbett + 3 zusätzliche Betten (90cm Matratze) nebeneinander, geräumig, Dusche/WC nächste Tür</p><p><br></p><p>1 Person&nbsp;- 44€ Zimmerpreis pro Nacht</p><p>2 Personen&nbsp;- 60€ Zimmerpreis pro Nacht</p><p>3 Personen&nbsp;- 75€ Zimmerpreis pro Nacht</p><p>4 Personen&nbsp;- 92€ Zimmerpreis pro Nacht</p><p>5 Personen&nbsp;- 100€ Zimmerpreis pro Nacht</p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/1_1635331081954.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/3_1635331094022.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/2_1635331104303.jpg"></p>',
    language: 'DE',
    ord: 3,
    page_id: 5,
    post_id: 21,
    title: 'Zimmer 3',
    type: 'article',
  },
  {
    content:
      '<p>Zimmer 4: 1. OG, 3x 90er Matratze, 2x Betten übereinander, 1x daneben, Dusche/WC nächste Tür</p><p><br></p><p>1 Person&nbsp;- 38€ Zimmerpreis pro Nacht</p><p>2 Personen&nbsp;- 54€ Zimmerpreis pro Nacht</p><p>3 Personen&nbsp;- 66€ Zimmerpreis pro Nacht</p><p><br></p><p class="ql-align-center"><img src="/pictures/2_1635331491316.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/1_1635331501189.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/3_1635331523692.jpg"></p>',
    language: 'DE',
    ord: 4,
    page_id: 5,
    post_id: 22,
    title: 'Zimmer 4',
    type: 'article',
  },
  {
    content:
      '<p>Zimmer 5: 1. OG, 2x 90er Matratze, Betten übereinander, Dusche/WC nächste Tür</p><p><br></p><p>1 Person&nbsp;- 38€ Zimmerpreis pro Nacht</p><p>2 Personen&nbsp;- 54€ Zimmerpreis pro Nacht</p><p><br></p><p class="ql-align-center"><img src="/pictures/1_1635331632552.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/2_1635331643144.jpg"></p>',
    language: 'DE',
    ord: 5,
    page_id: 5,
    post_id: 23,
    title: 'Zimmer 5',
    type: 'article',
  },
  {
    content:
      '<p>Zimmer 6: <span style="color: rgb(0, 0, 0);">1. OG, 1 Doppelbett + 3 zusätzliche Betten (90cm Matratze) nebeneinander, geräumig, Dusche/WC nächste Tür</span></p><p><br></p><p>1 Person&nbsp;- 44€ Zimmerpreis pro Nacht</p><p>2 Personen&nbsp;- 60€ Zimmerpreis pro Nacht</p><p>3 Personen&nbsp;- 75€ Zimmerpreis pro Nacht</p><p>4 Personen&nbsp;- 92€ Zimmerpreis pro Nacht</p><p>5 Personen&nbsp;- 100€ Zimmerpreis pro Nacht</p><p><br></p><p class="ql-align-center"><img src="/pictures/2_1635331769005.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/1_1635331779278.jpg"></p>',
    language: 'DE',
    ord: 6,
    page_id: 5,
    post_id: 24,
    title: 'Zimmer 6',
    type: 'article',
  },
  {
    content:
      '<p>Zimmer 7: 1. OG, großes Bett mit 160er Matratze (von beiden Seiten begehbar) und Hochbett mit 120er Matratze, geräumig, zimmereigene Dusche/WC abschließbar</p><p><br></p><p>1 Person&nbsp;- 49€ Zimmerpreis pro Nacht</p><p>2 Personen&nbsp;- 66€ Zimmerpreis pro Nacht</p><p>3 Personen&nbsp;- 75€ Zimmerpreis pro Nacht</p><p><br></p><p class="ql-align-center"><img src="/pictures/1_1635331872616.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/2_1635331881249.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/3_1635331892351.jpg"></p>',
    language: 'DE',
    ord: 7,
    page_id: 5,
    post_id: 25,
    title: 'Zimmer 7',
    type: 'article',
  },
  {
    content: '',
    language: 'DE',
    ord: 1,
    page_id: 6,
    post_id: 26,
    title: 'Anfahrt',
    type: 'map',
  },
  {
    content: '<p>Muskauer Straße 11</p><p>10997 Berlin Kreuzberg</p>',
    language: 'DE',
    ord: 2,
    page_id: 6,
    post_id: 27,
    title: 'adresse:',
    type: 'article',
  },
  {
    content: '',
    language: 'DE',
    ord: 2,
    page_id: 9,
    post_id: 29,
    title: '',
    type: 'message',
  },
  {
    content:
      '<p>Primitivo Puglie (trocken) 0,2l 3.80</p><p>Weisswein Verdejo Rueda (trocken) 0,2l 3.80</p><p>Weisswein Riesling Tesch (trocken) 0,2l 3.50</p><p>Sekt Sekoi (trocken) 0,1l 2.70</p><p>Sekt auf Eis 0,2l 4.50</p><p>Sekt-Aperol 0,2l 5.00</p>',
    language: 'DE',
    ord: 5,
    page_id: 2,
    post_id: 31,
    title: 'wein & sekt',
    type: 'drinks',
  },
  {
    content: '',
    language: 'DE',
    ord: 3,
    page_id: 2,
    post_id: 33,
    title: 'Getränke karte',
    type: 'article',
  },
  {
    content:
      "<p>Rock'n'Rolla 1.50</p><p>Mexicaner 1.50</p><p>Sauerer 1.50</p><p>Wodka Lime 1.50</p><p>Commander OLF 1.50</p><p>B 52 3</p>",
    language: 'DE',
    ord: 9,
    page_id: 2,
    post_id: 34,
    title: 'Selbstgemixt 2cl',
    type: 'drinks',
  },
  {
    content:
      '<p>Hemingway 4</p><p>Baileys 4</p><p>Ramazotti 4</p><p>Pernod Ricard 4</p>',
    language: 'DE',
    ord: 10,
    page_id: 2,
    post_id: 35,
    title: 'On the rocks 4cl',
    type: 'drinks',
  },
  {
    content:
      "<p>Finsbury Gin 4cl + Thomas Henry Tonic 0,2l 6</p><p>Bombay Gin 4cl + Thomas Henry Tonic 0,2l 7</p><p>Hendrick's Gin 4cl + Thomas Henry Tonic 0,2l 8</p><p>Monkey 47 Gin 4cl + Thomas Henry Tonic 0,2l 9</p><p>Futschi (2cl Weinbrand mit Cola) 2.50</p><p>Kornschorle (2cl Korn mit Sprudle) 2.50</p><p>Wodka 4cl + 0,25l Red Bull 6.50</p><p>Wodka 4cl + Mio Mio Mate 0,5l 6.50</p><p>Wodka 4cl + Filler (offen) 5.50</p><p>Wodka 4cl + Thomas Henry 0,2l/Saftflasche 0,2l 6</p>",
    language: 'DE',
    ord: 11,
    page_id: 2,
    post_id: 36,
    title: 'Longdrinks',
    type: 'drinks',
  },
  {
    content:
      "<p>Irish Mist Liqueur 4.50</p><p>Southern Comforter Liqueur 4.50</p><p>Four Rose's 4.50</p><p>Jim Bean 4.50</p><p>Jack Daniel's 5</p><p>Paddy Irish 4.50</p><p>Tullamore Dew Irish 4.50</p><p>Jameson Irish 4.50</p><p>Red Breats Irish (12 Jahre) 8.50</p><p>Laphroaig Scotch (10 Jahre) 8</p><p>Auchentoshan Scotch (12 Jahre) 8</p><p>Lagavulin Scotch (16 Jahre) 9</p><p><br></p><p>serviert im Tumbler, mit Filler (offen) +1</p><p>mit Thomas Henry 0,2l oder Saftflasche 0,2l +2</p>",
    language: 'DE',
    ord: 12,
    page_id: 2,
    post_id: 37,
    title: 'Whiskey &  artverwandtes',
    type: 'drinks',
  },
  {
    content:
      '<p class="ql-align-justify">The Hostel - a Living room with possibility to stay overnight.</p><p class="ql-align-justify">The 6 rooms with space for 1-5 persons are designed with love&nbsp;by several&nbsp;local artists.</p><p class="ql-align-justify">Tired&nbsp;musicians as well as open minded tourists should be comfortable at our house.</p><p class="ql-align-justify">The Concept is easy: we created a place for musicians and music-lovers to feel like home. Especially for bands on tour, our house is a very good alternative to the cramped tour bus or the clinical hotel.</p><p class="ql-align-justify">We offer WiFi in all our rooms. Our bar has got an outside-area, where you can enjoy your drinks or breakfast during the warmer times in the sun.</p><p class="ql-align-justify">We give you a huge assortment of drinks in our bar till the morning&nbsp;hours or open end.</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">In this spirit we\'re looking forward to welcome you and your friends here soon.</p><p><br></p><p class="ql-align-justify">We hope you understand!</p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><img src="/pictures/bar 1_1635330142076.jpg"></p><p class="ql-align-justify"><br></p><h2 class="ql-align-right">Your Hostel Team</h2><p class="ql-align-right"><br></p><h2 class="ql-align-justify"><strong>Warning:</strong>&nbsp;<em>Nazis, fascists, racists, homophobics, sexists and any other intolerant twats have to STAY OUT!!</em></h2>',
    language: 'EN',
    ord: 1,
    page_id: 10,
    post_id: 38,
    title: "We're looking forward to your visit!",
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-center">Our bar is also the reception for our rooms and opens every day at 4 p.m.</p><p class="ql-align-center">You can play billiard, booze or try one of our numerous juices.</p><p class="ql-align-center">We offer also Nachos (vegan or non-vegan) throughout our opening times.</p><p class="ql-align-center">Good music is for free!! ;-)</p><p><br></p><p><img src="/pictures/bar 2_1635330410885.jpg"></p>',
    language: 'EN',
    ord: 1,
    page_id: 11,
    post_id: 43,
    title: '',
    type: 'article',
  },
  {
    content: '',
    language: 'EN',
    ord: 3,
    page_id: 11,
    post_id: 46,
    title: 'Drinks',
    type: 'article',
  },
  {
    content:
      '<p>Rothause Tannenzäpfel 0,33l 2.60</p><p>Flensburger 0,33l 2.30</p><p>Bayreuther Hell 0,5l 3.10</p><p>Hopf Helles Hefeweizen 0,5l 3.40</p><p>Hopf Dunkles Hefeweizen 0,5l 3.40</p><p>Erdinger Kristall 0,5l 3.60</p><p>OSTMOST Cider wild 0,33l 3.30</p><p>Erdinger Hefeweizen alkoholfrei 0,5l 3.40</p><p>Rothaus Tannenzäpfle alkoholfrei 0,33l 2.60</p>',
    language: 'DE',
    ord: 6,
    page_id: 2,
    post_id: 48,
    title: 'Flaschenbier',
    type: 'drinks',
  },
  {
    content:
      '<p>Hausmarke 0,4l (auch Radler oder Diesel) 2.80</p><p>Pilsner Urquell 0,3l (auch Radler oder Diesel) 2.60</p><p>Pilsner Urquell 0,5l (auch Radler oder Diesel) 3.60</p><p>Rothaus Pils 0,3l (auch Radler oder Diesel) 2.80</p><p>Rothaus Pils 0,5l (auch Radler oder Diesel) 3.80</p><p>Rollberg Rotbier 0,3l 2.90</p><p>Rollberg Rotbier 0,5l 3.90</p><p>Snakebite 0,5l 4.70</p>',
    language: 'EN',
    ord: 4,
    page_id: 11,
    post_id: 49,
    title: 'On tap',
    type: 'drinks',
  },
  {
    content:
      '<p>Rothause Tannenzäpfel 0,33l 2.60</p><p>Flensburger 0,33l 2.30</p><p>Bayreuther Hell 0,5l 3.10</p><p>Hopf Helles Hefeweizen 0,5l 3.40</p><p>Hopf Dunkles Hefeweizen 0,5l 3.40</p><p>Erdinger Kristall 0,5l 3.60</p><p>OSTMOST Cider wild 0,33l 3.30</p><p>Erdinger Hefeweizen alkoholfrei 0,5l 3.40</p><p>Rothaus Tannenzäpfle alkoholfrei 0,33l 2.60</p>',
    language: 'EN',
    ord: 6,
    page_id: 11,
    post_id: 50,
    title: 'Bottled beers',
    type: 'drinks',
  },
  {
    content:
      '<p>Primitivo Puglie (trocken) 0,2l 3.80</p><p>Weisswein Verdejo Rueda (trocken) 0,2l 3.80</p><p>Weisswein Riesling Tesch (trocken) 0,2l 3.50</p><p>Sekt Sekoi (trocken) 0,1l 2.70</p><p>Sekt auf Eis 0,2l 4.50</p><p>Sekt-Aperol 0,2l 5.00</p>',
    language: 'EN',
    ord: 5,
    page_id: 11,
    post_id: 51,
    title: 'wine & sparkling wine',
    type: 'drinks',
  },
  {
    content:
      '<p>Berliner Luft 1.50</p><p>Waldmeister 1.50</p><p>Echter Nordhäuser Dopplekorn 1.50</p><p>Kümmeling 1.50</p><p>Eierlikör 1.50</p><p>Jägermeister 2</p><p>Sambuca 2</p><p>Vodka <span style="color: rgb(0, 0, 0);">(diverse Sorten)</span> 2</p><p>Linie Aquavit 2.50</p><p>Brandy (103er, Osborne, Veterano) 2.50</p><p>Obstbrand 2.50</p><p>Mescal 2.50</p><p>Tequila Corralejo Blanco (silber) 2.50</p><p>Tequila Corralejo Reposado (braun) 2.50</p><p>Tequila Corralejo Anejo (braun) 2.50</p>',
    language: 'DE',
    ord: 8,
    page_id: 2,
    post_id: 53,
    title: 'Shots 2cl',
    type: 'drinks',
  },
  {
    content:
      "<p>Rock'n'Rolla 1.50</p><p>Mexicaner 1.50</p><p>Sauerer 1.50</p><p>Wodka Lime 1.50</p><p>Commander OLF 1.50</p><p>B 52 3</p>",
    language: 'EN',
    ord: 9,
    page_id: 11,
    post_id: 54,
    title: 'Homemade mix 2cl',
    type: 'drinks',
  },
  {
    content:
      '<p>Hemingway 4</p><p>Baileys 4</p><p>Ramazotti 4</p><p>Pernod Ricard 4</p>',
    language: 'EN',
    ord: 10,
    page_id: 11,
    post_id: 55,
    title: 'On the rocks 4cl',
    type: 'drinks',
  },
  {
    content:
      "<p>Finsbury Gin 4cl + Thomas Henry Tonic 0,2l 6</p><p>Bombay Gin 4cl + Thomas Henry Tonic 0,2l 7</p><p>Hendrick's Gin 4cl + Thomas Henry Tonic 0,2l 8</p><p>Monkey 47 Gin 4cl + Thomas Henry Tonic 0,2l 9</p><p>Futschi (2cl Weinbrand mit Cola) 2.50</p><p>Kornschorle (2cl Korn mit Sprudle) 2.50</p><p>Wodka 4cl + 0,25l Red Bull 6.50</p><p>Wodka 4cl + Mio Mio Mate 0,5l 6.50</p><p>Wodka 4cl + Filler (offen) 5.50</p><p>Wodka 4cl + Thomas Henry 0,2l/Saftflasche 0,2l 6</p>",
    language: 'EN',
    ord: 11,
    page_id: 11,
    post_id: 56,
    title: 'Longdrinks',
    type: 'drinks',
  },
  {
    content:
      "<p>Irish Mist Liqueur 4.50</p><p>Southern Comforter Liqueur 4.50</p><p>Four Rose's 4.50</p><p>Jim Bean 4.50</p><p>Jack Daniel's 5</p><p>Paddy Irish 4.50</p><p>Tullamore Dew Irish 4.50</p><p>Jameson Irish 4.50</p><p>Red Breats Irish (12 Jahre) 8.50</p><p>Laphroaig Scotch (10 Jahre) 8</p><p>Auchentoshan Scotch (12 Jahre) 8</p><p>Lagavulin Scotch (16 Jahre) 9</p><p><br></p><p>serviert im Tumbler, mit Filler (offen) +1</p><p>mit Thomas Henry 0,2l oder Saftflasche 0,2l +2</p>",
    language: 'EN',
    ord: 12,
    page_id: 11,
    post_id: 57,
    title: 'Whiskey',
    type: 'drinks',
  },
  {
    content:
      '<p>Everyday from 4p.m. until Open End!</p><p></p><p>Closed on may 15th.</p><p><br/><p>Muster Str. 11</p><p>11117 Berlin</p>',
    language: 'EN',
    ord: 2,
    page_id: 11,
    post_id: 59,
    title: 'Opening hours',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/backbord-menü-english_1650967184381.jpg"></p>',
    language: 'EN',
    ord: 1,
    page_id: 12,
    post_id: 60,
    title: 'Every Tuesday',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/everythursday_1630609757954.jpg"></p>',
    language: 'EN',
    ord: 2,
    page_id: 12,
    post_id: 61,
    title: 'Every Thursday',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-justify">All prices including VAT and City-Tax.</p><p class="ql-align-justify">Please understand that you have pay a cancellation fee if you cancel if you cancel after 3 days prior to arrival or if you don\'t come without canceling at all. More information in our&nbsp;<em>AGBs</em>&nbsp;(sorry, AGBs only in German language).</p><p class="ql-align-justify"><br></p><p class="ql-align-justify">Check-in from 5 p.m., checkout until 2 p.m.</p><p class="ql-align-justify">For late Check-in (after 12p.m.)</p><p class="ql-align-justify">For checkout just put the key in the lock from the inside of your room.</p><p class="ql-align-justify">We never rent the rooms to different parties, regardless of how many bed there are in the room. You\'ll have it for yourself!</p><p class="ql-align-center"><br></p><p class="ql-align-center"><span style="color: rgb(230, 0, 0);">ATTENTION:</span></p><p class="ql-align-center"><span style="color: black;">Sometimes it can take up to 48 hours before we get back to you. So if you want to book a room on the same day of the request or for the next day, please call 030-XXX XXX XX from 4pm to book it by phone.</span></p><p class="ql-align-center"><br></p><p class="ql-align-center"><br></p>',
    language: 'EN',
    ord: 1,
    page_id: 13,
    post_id: 62,
    title: 'How to book a room',
    type: 'article',
  },
  {
    content:
      '<p>Room 1: first floor. Bunk bed with 140cm mattress above, 90cm mattress below, shower/wc in the room (not lockable).</p><p><br></p><p>1 person - 38€ /price per night</p><p>2 persons&nbsp;- 54€ /price per night</p><p>3 persons&nbsp;- 66€ /price per night</p><p><br></p><p><img src="/pictures/test_1631018829575.jpg"> <img src="/pictures/test2_1631018839793.jpg"></p>',
    language: 'EN',
    ord: 2,
    page_id: 13,
    post_id: 63,
    title: 'Room 1',
    type: 'article',
  },
  {
    content:
      '<p>Room 3: 1st floor, 1 double bed + 3 additional beds (<span style="color: rgb(0, 0, 0);">90cm mattress)</span> side by side, spacious, shower/WC next door.</p><p><br></p><p>1 person&nbsp;- 44€ /price per night</p><p>2 persons - 60€ /price per night</p><p>3 persons- 75€ /price per night</p><p>4 persons- 92€ /price per night</p><p>5 persons- 100€ /price per night</p><p><br></p><p class="ql-align-center"><img src="/pictures/1_1635331424510.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/3_1635331433757.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/2_1635331447728.jpg"></p>',
    language: 'EN',
    ord: 3,
    page_id: 13,
    post_id: 64,
    title: 'Room 3',
    type: 'article',
  },
  {
    content:
      '<p>Room 5: 1st floor, one bunk bed with 90cm mattress, shower/WC next door</p><p><br></p><p>1 person&nbsp;- 38€ /price per night</p><p>2 persons - 54€ /price per night</p><p><br></p><p class="ql-align-center"><img src="/pictures/1_1635331666247.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/2_1635331674769.jpg"></p>',
    language: 'EN',
    ord: 5,
    page_id: 13,
    post_id: 65,
    title: 'Room 5',
    type: 'article',
  },
  {
    content:
      '<p>Room 6: <span style="color: rgb(0, 0, 0);">1st floor, 1 double bed + 3 additional beds (90cm mattress) side by side, spacious, shower/WC next door.</span></p><p><br></p><p>1 person&nbsp;- 44€ /price per night</p><p>2 persons - 60€ /price per night</p><p>3 persons- 75€ /price per night</p><p>4 persons- 92€ /price per night</p><p>5 persons- 100€ /price per night</p><p><br></p><p class="ql-align-center"><img src="/pictures/2_1635331824438.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/1_1635331836214.jpg"></p>',
    language: 'EN',
    ord: 6,
    page_id: 13,
    post_id: 66,
    title: 'Room 6',
    type: 'article',
  },
  {
    content:
      '<p>Room 7: 1st floor, double bed with 160cm mattress (accessible from both sides) and a loft bed with 120cm mattress, spacious, shower/WC lockable</p><p><br></p><p>1 person&nbsp;- 49€ /price per night</p><p>2 persons - 66€ /price per night</p><p>3 persons - 75€ /price per night</p><p><br></p><p class="ql-align-center"><img src="/pictures/1_1635331920075.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/2_1635331929822.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/3_1635331936745.jpg"></p>',
    language: 'EN',
    ord: 7,
    page_id: 13,
    post_id: 67,
    title: 'Room 7',
    type: 'article',
  },
  {
    content: '',
    language: 'EN',
    ord: 1,
    page_id: 14,
    post_id: 69,
    title: '',
    type: 'map',
  },
  {
    content: '<p>Muskauer Straße 11</p><p>10997 Berlin Kreuzberg</p>',
    language: 'EN',
    ord: 2,
    page_id: 14,
    post_id: 70,
    title: 'address:',
    type: 'article',
  },
  {
    content: '',
    language: 'EN',
    ord: 2,
    page_id: 15,
    post_id: 72,
    title: '',
    type: 'message',
  },
  {
    content:
      '<p>Room 4: 1st floor, one bunk bed with 90cm mattress, and one bed with a 90cm mattress, shower/WC next door.</p><p><br></p><p>1 person&nbsp;- 38€ /price per night</p><p>2 persons - 54€ /price per night</p><p>3 persons - 66€ /price per night</p><p><br></p><p class="ql-align-center"><img src="/pictures/2_1635331563998.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/1_1635331577926.jpg"></p><p class="ql-align-center"><br></p><p class="ql-align-center"><img src="/pictures/3_1635331586445.jpg"></p>',
    language: 'EN',
    ord: 4,
    page_id: 13,
    post_id: 73,
    title: 'Room 4',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-justify"><strong>Impressum</strong></p> </p><p class="ql-align-justify"><em>Quelle: Impressum erzeugt mit dem Impressum Generator von eRecht24.</em></p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><br></p><p class="ql-align-justify"><strong>Haftungsausschluss:</strong></p><p class="ql-align-justify">Haftung für Inhalte</p><p class="ql-align-justify">Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p><p class="ql-align-justify">Haftung für Links</p><p class="ql-align-justify">Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p><p class="ql-align-justify">Urheberrecht</p><p class="ql-align-justify">Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p><p class="ql-align-justify">Datenschutz</p><p class="ql-align-justify">Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.</p><p class="ql-align-justify">Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.</p><p class="ql-align-justify">Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.</p><p class="ql-align-justify"><em>Quelle: Disclaimer von eRecht24, dem Portal zum Internetrecht von Rechtsanwalt</em></p><p class="ql-align-justify"><em>Sören Siebert.</em></p><p class="ql-align-justify"><strong>Allgemeine Geschäftsbedingungen für die Buchung eines Zimmers in unserem Hotel</strong></p><p class="ql-align-justify"><strong>Geltungsbereich</strong></p><p class="ql-align-justify">Diese Geschäftsbedingungen gelten für die Verträge über die mietweise Überlassung von Hotelzimmern zur Beherbergung sowie alle für den Kunden erbrachten weiteren Leistungen und Lieferungen des Hotels.</p><p class="ql-align-justify"><strong>Vertragsabschluss, -partner, -haftung; Verjährung</strong></p><p class="ql-align-justify">- Der Vertrag kommt durch die Annahme des Antrages des Kunden durch das Hotel zustande. Dem Hotel steht es frei, die Zimmerbuchung schriftlich zu bestätigen.</p><p class="ql-align-justify">- Vertragspartner sind das Hotel und der Kunde. Hat ein Dritter für den Kunden bestellt, haftet er dem Hotel gegenüber zusammen mit dem Kunden als Gesamtschuldner für alle Verpflichtungen aus dem Hotelaufnahmevertrag, sofern dem Hotel eine entsprechende Erklärung des Dritten vorliegt.</p><p class="ql-align-justify">- Das Hotel haftet für seine Verpflichtungen aus dem Vertrag. Im nicht leistungstypischen Bereich ist die Haftung auf Vorsatz und grobe Fahrlässigkeit des Hotels beschränkt.</p><p class="ql-align-justify"><strong>Leistungen, Preise, Zahlung, Aufrechnung</strong></p><p class="ql-align-justify">- Das Hotel ist verpflichtet, die vom Kunden gebuchten Zimmer bereitzuhalten und die vereinbarten Leistungen zu erbringen.- Der Kunde ist verpflichtet, die für die Zimmerüberlassung und die von ihm in Anspruch genommenen weitere Leistungen geltenden bzw. vereinbarten Preise des Hotels spätestens bei Abreise zu zahlen. Dies gilt auch für vom Kunden veranlasste Leistungen und Auslagen des Hotels an Dritte.- Rechnungen des Hotels ohne Fälligkeitsdatum sind binnen 10 Tagen ab Zugang der Rechnung ohne Abzug zahlbar. Das Hotel ist berechtigt aufgelaufene Forderungen jederzeit fällig zu stellen und unverzügliche Zahlung zu verlangen. Bei Zahlungsverzug ist das Hotel berechtigt, Zinsen in Höhe- von 5% über dem jeweiligen Basiszinssatz bzw. dem entsprechenden Nachfolgezinssatz der Europäischen Zentralbank zu berechnen. Dem Kunden bleibt der Nachweis eines niedrigeren, dem Hotel des eines höheren Schadens vorbehalten. - Das Hotel ist berechtigt, bei Vertragsschluss oder danach, unter Berücksichtigung der rechtlichen Bestimmungen für Pauschalreisen eine angemessene Vorauszahlung oder Sicherheitsleistung zu verlangen. Die Höhe der Vorauszahlung und die Zahlungstermine können im Vertrag schriftlich vereinbart werden.- Der Kunde kann nur mit einer unstreitigen oder rechtskräftigen Forderung gegenüber einer Forderung des Hotels aufrechnen oder mindern.</p><p class="ql-align-justify"><strong>Rücktritt des Kunden (Abbestellung, Stornierung)</strong></p><p class="ql-align-justify">- Eine garantierte Reservierung liegt dann vor, wenn der Gast die Übernachtungsdienstleistung mündlich vor Ort, per Telefon oder schriftlich oder per Email bestätigt und die bestellten Zimmer nicht 7 Tage vor der Anreise storniert. Wird das Zimmer in den letzten 7 Tagen vor Anreise storniert, muss dies telefonisch erfolgen.</p><p class="ql-align-justify">Bis 7 Tage vor Anreise ist die Stornierung kostenfrei. Bei einer Stornierung bis 24 Stunden vor Anreise beträgt die Stornierungsgebühr 50% der Gesamtbuchung, danach 90% der Gesamtbuchung.</p><p class="ql-align-justify">Bei Nichterscheinen des Gastes (No Show) wird der volle Betrag des gebuchten Aufenthaltes abzüglich etwa ersparter Aufwendungen berechnet.</p><p class="ql-align-justify"><strong>Rücktritt des Hotels</strong></p><p class="ql-align-justify">- Wird eine vereinbarte Vorauszahlung auch nach Verstreichen einer vom Hotel gesetzten angemessenen Nachfrist mit Ablehnungsandrohung nicht geleistet, so ist das Hotel ebenfalls zum Rücktritt vom Vertrag berechtigt.</p><p class="ql-align-justify">- Ferner ist das Hotel berechtigt, aus sachlich gerechtfertigtem Grund vom Vertrag außerordentlich zurückzutreten, beispielsweise falls</p><p class="ql-align-justify">- höhere Gewalt oder andere vom Hotel nicht zu vertretende Umstände die Erfüllung des Vertrages unmöglich machen;- Zimmer unter irreführender oder falscher Angabe wesentlicher Tatsachen, z.B. in der Person des Kunden oder des Zwecks, gebucht werden;- das Hotel begründeten Anlass zu der Annahme hat, dass die Inanspruchnahme der Hotelleistung den reibungslosen Geschäftsbetrieb, die Sicherheit oder das Ansehen des Hotels in der Öffentlichkeit gefährden kann, ohne dass dies dem Herrschafts- bzw. Organisationsbereich des Hotels zuzurechnen ist;- ein Verstoß gegen obigen Geltungsbereich vorliegt.- Das Hotel hat den Kunden von der Ausübung des Rücktrittsrechts unverzüglich in Kenntnis zu setzen.- Bei berechtigtem Rücktritt des Hotels entsteht kein Anspruch des Kunden auf Schadensersatz.</p><p class="ql-align-justify"><strong>Zimmerbereitstellung, -übergabe, -rückgabe</strong></p><p class="ql-align-justify">- Gebuchte Zimmer stehen dem Kunden ab 17.00 Uhr des vereinbarten Anreisetages zur Verfügung.- Am vereinbarten Abreisetag sind die Zimmer dem Hotel spätestens um 14.00 Uhr geräumt zur Verfügung zu stellen. Danach kann das Hotel über den ihm dadurch entstehenden Schaden hinaus für die zusätzliche Nutzung des Zimmers nach 14.00 Uhr 10,- € pro angefangener Stunde in Rechnung zu stellen.</p><p class="ql-align-justify"><strong>Zahlungsmittel/Dienstleistungen auf später zu bezahlende Rechnungen</strong></p><p class="ql-align-justify">- Gültige Zahlungsmittel sind Bargeld in Euro und Überweisung.</p><p class="ql-align-justify"><strong>Haftung des Hotels</strong></p><p class="ql-align-justify">- Für die unbeschränkte Haftung des Hotels gelten die gesetzlichen Bestimmungen. Schadensersatzansprüche, außer wegen grober Fahrlässigkeit oder Vorsatz, sind ausgeschlossen.</p><p class="ql-align-justify">- Gegenstände oder Materialien, die in&nbsp;allgemein zugänglichen Räumen des Hotels, in den technischen Einrichtungen und in der Lounge des Hotels hinterlassen werden, gelten nicht als eingebracht. Das Hotel ist nicht Verwahrer der vom Kunden ins Hotelzimmer eingebrachten Gegenstände, gleich welcher Art diese auch sind, und haftet daher nicht für deren Schicksal, dies gilt insbesondere für sogenannte Wertgegenstände. Es wird ausdrücklich darauf hingewiesen, dass das Hotel keine Aufbewahrungsmöglichkeit in einem Hotelsafe oder ähnlichen Sicherheitsbehältnissen bietet. Die Einbringung durch den Gast erfolgt daher auf dessen eigene Gefahr. Das Hotel ist ebenfalls nicht Verwahrer für im Hotel belassene Koffer, Taschen oder Sonstiges, die nach Räumung der Zimmer im Hotel, auch in dafür zur Verfügung stehenden Räumen, belassen und später abgeholt werden.</p><p class="ql-align-justify"><strong>Schlussbestimmungen</strong></p><p class="ql-align-justify">- Änderungen oder Ergänzungen des Vertrags, der Antragsannahme oder dieser Geschäftsbedingungen für die Hotelaufnahme sollen schriftlich erfolgen. Einseitige Änderungen oder Ergänzungen durch den Kunden sind unwirksam.- Erfüllungs- und Zahlungsort ist der Sitz des Hotels.- Ausschließlicher Gerichtsstand – auch für Scheck- und Wechselstreitigkeiten – ist im kaufmännischen Verkehr der Sitz des Hotels.- Es gilt deutsches Recht.- Sollten einzelne Bestimmungen dieser Allgemeinen Geschäftsbedingungen für die Hotelaufnahme unwirksam oder nichtig sein oder werden, so wird dadurch die Wirksamkeit der übrigen Bestimmungen nicht berührt. Im Übrigen gelten die gesetzlichen Vorschriften.</p>',
    language: 'DE',
    ord: 3,
    page_id: 9,
    post_id: 75,
    title: 'ABG & Imperessum',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-justify">Angaben gemäß § 5 TMG:</p><p class="ql-align-justify">Muster Str. 11</p><p class="ql-align-justify">10997 Berlin</p><p class="ql-align-justify"><br></p><p class="ql-align-justify">Vertreten durch:</p><p class="ql-align-justify">Max Mustermann</p><p class="ql-align-justify"><br></p></p><p class="ql-align-justify"><em>Quelle: Impressum erzeugt mit dem Impressum Generator von eRecht24.</em></p><p class="ql-align-justify"><br></p>',
    language: 'EN',
    ord: 3,
    page_id: 15,
    post_id: 77,
    title: 'company details',
    type: 'article',
  },
  {
    content:
      "<p>Sailor Jerr's Spiced Rum 5</p><p>Havanna Club 3 Jahre 4</p><p>Havanna Club 7 Jahre 6</p><p>Kraken Black Spiced Rum 5</p><p>Botucal Blanco 5</p><p>Botucal Reserve Exclusiva 6</p><p><br></p><p>serviert im Tumbler, mit Filler (offen) +1</p><p>mit Thomas Henry 0,2l oder Saftflasche 0,2l +2</p><p><br></p>",
    language: 'DE',
    ord: 13,
    page_id: 2,
    post_id: 78,
    title: 'Rum 4cl',
    type: 'drinks',
  },
  {
    content:
      '<p>Cuba Libre 6</p><p>Caipirinha 6</p><p>Mojito 6</p><p>White Russian "Big Lebowsky" Style 6</p><p>Whisky Sour/ Wodka Sour 6</p><p>Moloko Plus (süß - cremig) 6.50</p><p>Happy Tiger (süß - cremig) 6.50</p><p>Moscow Mule 6.50</p><p><br></p>',
    language: 'DE',
    ord: 13,
    page_id: 2,
    post_id: 79,
    title: 'Cocktails',
    type: 'drinks',
  },
  {
    content:
      '<p>Viva con Aqua (Mineralwasser) 0,33l&nbsp;2</p><p>Zitronenlimonade 0,2l/0,4l 1/1.180</p><p>Orangenlimonade 0,2l/0,4l 1/1.80</p><p>Rixdorfer Fassbrause 1.80/3</p><p>Coca Cola 0,2l/0,4l 1.80/3</p><p>Coca Cola Zero 0,2l/0,4l 1.80/3</p><p>Spezi 0,2l/0,4l 1.80/3</p><p>Apfelsaft&nbsp;0,2l/0,4l 2/3.50</p><p>Orangensaft&nbsp;0,2l/0,4l 2/3.50</p><p>Maracujanektar&nbsp;0,2l/0,4l 2/3.50</p><p>als Saftschorle&nbsp;0,2l/0,4l 1.80/3</p><p>Bananenfruchtsaftgetränk 0,2l 2.20</p><p>Kirschfruchtsaftgetränk 0,2l 2.20</p><p>Mangonektar 0,2l 2.20</p><p>Schwarzer Johannisbeernektar 0,2l 2.20</p><p>als Saftschorle 0,4l 3</p><p>Kiba 0,4l 3.50</p><p>Thomas Henry Ginger Ale 0,2l Flasche 2.20</p><p>Thomas Henry Bitter Lemon 0,2l Flasche 2.20</p><p>Thomas Henry Tonic Water 0,2l 2.20</p><p>Thomas Henry Spicy Ginger 0,2l 2.20</p><p>Red Bull Dose 0,25l 3</p><p>Kraftmalz 0,33l 2</p><p>Mio Mio Mate 0,5l 3</p><p>hausgemachter Eistee (Sommer) 0,2l/0,4l 1.80/3</p><p><br></p>',
    language: 'DE',
    ord: 14,
    page_id: 2,
    post_id: 80,
    title: 'Akoholfreies',
    type: 'drinks',
  },
  {
    content:
      "<p>Kaffee klein 1.50</p><p>Kaffe groß 2.50</p><p>Espresso 1.50</p><p>Milchkaffee 2.50</p><p>Latte Macchiato 3</p><p>Cappuccino 2</p><p>Heiße Schokolade mit Milch 2.20</p><p>Heiße Schokolade mit Milch und Sahne 2.50</p><p>Eiskaffee 3</p><p>Carajillo (Espresso mit 2cl Brandy) 3</p><p>Irish Coffee (mit Tullamore Dew Irish Whiskey) 4</p><p>hausgemachter Glühwein (Winter) 2.50</p><p>Grog 2.50</p><p>Tee (diverse Sorten) 1.50</p><p>Rock'n'Roll - Tee (mit frischer Minze und Honig)</p><p>Alle Milchgetränke gibt es auch mit Sojamilch (ohne Aufpreis)</p><p>Alle Heissgetränke auf Wunsch mit Schuss +1</p><p><br></p>",
    language: 'DE',
    ord: 15,
    page_id: 2,
    post_id: 81,
    title: 'Heissegetränke',
    type: 'drinks',
  },
  {
    content:
      '<p>Erdnüsse 1</p><p>Nachos mit hausgemachter Salsa 3.50</p><p>mit Käse 5</p><p>Bulette (auch Vegan) mit Brot 3</p><p>mit hausgemachten Kartoffelsalat 4.50</p><p><br></p>',
    language: 'DE',
    ord: 16,
    page_id: 2,
    post_id: 82,
    title: 'Snacks',
    type: 'drinks',
  },
  {
    content:
      '<p class="ql-align-justify">Wir freuen uns immer sehr über jede Form von Anmerkungen, konstruktiver Kritik oder Lob.</p><p class="ql-align-justify">Bitte kontaktiert uns!!</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">Zimmerbuchungen bitte nur über das <a href="http://www.rnrherberge.de/zimmerbuchen?language=DE" rel="noopener noreferrer" target="_blank">Buchungsformular</a>!</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">Fragen und Anmerkungen aller Art gerne in das Kontaktformular unten</p>',
    language: 'DE',
    ord: 1,
    page_id: 9,
    post_id: 87,
    title: 'Kontakt',
    type: 'article',
  },
  {
    content:
      '<p>We like to know what you think!!</p><p class="ql-align-justify">For any questions or feedback, please contact us using the form below.</p><p class="ql-align-justify">&nbsp;</p><p class="ql-align-justify">For rooms reservation please use the <a href="http://www.rnrherberge.de/bookaroom?language=EN" rel="noopener noreferrer" target="_blank">Book a Room</a>!</p>',
    language: 'EN',
    ord: 1,
    page_id: 15,
    post_id: 88,
    title: 'Contact',
    type: 'article',
  },
  {
    content:
      '<p>Berliner Luft 1.50</p><p>Waldmeister 1.50</p><p>Echter Nordhäuser Dopplekorn 1.50</p><p>Kümmeling 1.50</p><p>Eierlikör 1.50</p><p>Jägermeister 2</p><p>Sambuca 2</p><p>Vodka 2 (different brands)</p><p>Linie Aquavit 2.50</p><p>Brandy (103er, Osborne, Veterano) 2.50</p><p>Obstbrand (different sorts) 2.50</p><p>Mescal 2.50</p><p>Tequila Corralejo Blanco (silber) 2.50</p><p>Tequila Corralejo Reposado (braun) 2.50</p><p>Tequila Corralejo Anejo (braun) 2.50</p>',
    language: 'EN',
    ord: 8,
    page_id: 11,
    post_id: 97,
    title: 'Shots 2cl',
    type: 'drinks',
  },
  {
    content:
      "<p>Sailor Jerr's Spiced Rum 5</p><p>Havanna Club 3 Jahre 4</p><p>Havanna Club 7 Jahre 6</p><p>Kraken Black Spiced Rum 5</p><p>Botucal Blanco 5</p><p>Botucal Reserve Exclusiva 6</p><p><br></p><p>serviert im Tumbler, mit Filler (offen) +1</p><p>mit Thomas Henry 0,2l oder Saftflasche 0,2l +2</p>",
    language: 'EN',
    ord: 13,
    page_id: 11,
    post_id: 98,
    title: 'Rum 4cl',
    type: 'drinks',
  },
  {
    content:
      '<p>Cuba Libre 6</p><p>Caipirinha 6</p><p>Mojito 6</p><p>White Russian "Big Lebowsky" Style 6</p><p>Whisky Sour/ Wodka Sour 6</p><p>Moloko Plus (süß - cremig) 6.50</p><p>Happy Tiger (süß - cremig) 6.50</p><p>Moscow Mule 6.50</p>',
    language: 'EN',
    ord: 13,
    page_id: 11,
    post_id: 127,
    title: 'Cocktails',
    type: 'drinks',
  },
  {
    content:
      '<p>Viva con Aqua (Mineralwasser) 0,33l&nbsp;2</p><p>Zitronenlimonade 0,2l/0,4l 1/1.180</p><p>Orangenlimonade 0,2l/0,4l 1/1.80</p><p>Rixdorfer Fassbrause 1.80/3</p><p>Coca Cola 0,2l/0,4l 1.80/3</p><p>Coca Cola Zero 0,2l/0,4l 1.80/3</p><p>Spezi 0,2l/0,4l 1.80/3</p><p>Apfelsaft&nbsp;0,2l/0,4l 2/3.50</p><p>Orangensaft&nbsp;0,2l/0,4l 2/3.50</p><p>Maracujanektar&nbsp;0,2l/0,4l 2/3.50</p><p>als Saftschorle&nbsp;0,2l/0,4l 1.80/3</p><p>Bananenfruchtsaftgetränk 0,2l 2.20</p><p>Kirschfruchtsaftgetränk 0,2l 2.20</p><p>Mangonektar 0,2l 2.20</p><p>Schwarzer Johannisbeernektar 0,2l 2.20</p><p>als Saftschorle 0,4l 3</p><p>Kiba 0,4l 3.50</p><p>Thomas Henry Ginger Ale 0,2l Flasche 2.20</p><p>Thomas Henry Bitter Lemon 0,2l Flasche 2.20</p><p>Thomas Henry Tonic Water 0,2l 2.20</p><p>Thomas Henry Spicy Ginger 0,2l 2.20</p><p>Red Bull Dose 0,25l 3</p><p>Kraftmalz 0,33l 2</p><p>Mio Mio Mate 0,5l 3</p><p>hausgemachter Eistee (Sommer) 0,2l/0,4l 1.80/3</p><p><br></p>',
    language: 'EN',
    ord: 14,
    page_id: 11,
    post_id: 128,
    title: 'alcohol free',
    type: 'drinks',
  },
  {
    content:
      "<p>Kaffee klein 1.50</p><p>Kaffe groß 2.50</p><p>Espresso 1.50</p><p>Milchkaffee 2.50</p><p>Latte Macchiato 3</p><p>Cappuccino 2</p><p>Heiße Schokolade mit Milch 2.20</p><p>Heiße Schokolade mit Milch und Sahne 2.50</p><p>Eiskaffee 3</p><p>Carajillo (Espresso mit 2cl Brandy) 3</p><p>Irish Coffee (mit Tullamore Dew Irish Whiskey) 4</p><p>hausgemachter Glühwein (Winter) 2.50</p><p>Grog 2.50</p><p>Tee (diverse Sorten) 1.50</p><p>Rock'n'Roll - Tee (mit frischer Minze und Honig)</p><p>Alle Milchgetränke gibt es auch mit Sojamilch (ohne Aufpreis)</p><p>Alle Heissgetränke auf Wunsch mit Schuss +1</p><p><br></p>",
    language: 'EN',
    ord: 15,
    page_id: 11,
    post_id: 129,
    title: 'Hot Drinks',
    type: 'drinks',
  },
  {
    content:
      '<p>Erdnüsse 1</p><p>Nachos mit hausgemachter Salsa 3.50</p><p>mit Käse 5</p><p>Bulette (auch Vegan) mit Brot 3</p><p>mit hausgemachten Kartoffelsalat 4.50</p>',
    language: 'EN',
    ord: 16,
    page_id: 11,
    post_id: 130,
    title: 'Snacks',
    type: 'drinks',
  },
  {
    content:
      '<p class="ql-align-center"><img src="/pictures/281877478_4974768402641906_1709775512194496983_n_1654343078057.jpg"></p>',
    language: 'DE',
    ord: '',
    page_id: 66,
    post_id: 154,
    title: '10.06. acoustic gig abend',
    type: 'article',
  },
  {
    content:
      '<p class="ql-align-center"><img src="/pictures/281877478_4974768402641906_1709775512194496983_n_1654343116893.jpg"></p>',
    language: 'EN',
    ord: '',
    page_id: 67,
    post_id: 155,
    title: '10.06. acoustic gig evening',
    type: 'article',
  },
  {
    content: '',
    language: 'DE',
    ord: 11,
    page_id: 5,
    post_id: 156,
    title: 'booking',
    type: 'booking',
  },
];
